### ISSUE TITLE
Return value of assigned result

### ISSUE THREAD

**Issue by phipsgabler** [ahwillia/Einsum.jl#22]
This is a different behaviour from `TensorOperations.jl`:

```
julia> @tensor r[k] := x[i] * M[k, i, j] * x[j]
5-element Array{Float64,1}:
 2.11926
 2.22626
 2.99243
 2.30047
 1.65922

julia> @einsum r[k] := x[i] * M[k, i, j] * x[j]

julia> r
5-element Array{Float64,1}:
 2.11926
 2.22626
 2.99243
 2.30047
 1.65922
```

I find it more natural if the result of an assignment is also immediately returned, that's basically what happens normally in Julia. Or was that a deliberate choice?

**Comment by ahwillia** [comment]
It wasn't deliberate. This could be changed.

**Comment by phipsgabler** [comment]
Ok. I think I could make a pull request for this, then, when I find the time.
