### ISSUE TITLE
Julia 0.6   deprecation warning messages

### ISSUE THREAD

**Issue by RaulDurand** [ahwillia/Einsum.jl#26]
When using Einsum in Julia 0.6 we get the message:
```
WARNING: Array{T}(::Type{T}, m::Int, n::Int, o::Int) is deprecated, use Array{T}(m, n, o) instead.
```

**Comment by phipsgabler** [comment]
As far as I can see, there is only one place where `Array` is used, and that has been [updated](https://github.com/ahwillia/Einsum.jl/commit/41a76132b4e2d59ec45cbbdd4919a989ea14f27e) some time ago to remove this warning. 

Which version are you using? Can you try to narrow down the problem?

**Comment by ahwillia** [comment]
They are fixed on master but we should tag a new version so that users don't need to run `Pkg.checkout("Einsum")`. Usually this is done with:

```julia
julia> PkgDev.tag("Einsum")
julia> PkgDev.publish()
```

But I'm running into an error, https://github.com/JuliaLang/PkgDev.jl/issues/101

**Comment by mcabbott** [comment]
Note that in #29 I added Compat, so that the `undef` syntax should work on both 1.0 and 0.6. But this error looks like it might be from a version for julia before 0.6.

**Comment by phipsgabler** [comment]
Seems to work on the [current 0.6 build](https://travis-ci.org/ahwillia/Einsum.jl/jobs/477920450), and should be fixed in the next published release.
