### ISSUE TITLE
Clarification about einsimd

### ISSUE THREAD

**Issue by phipsgabler** [ahwillia/Einsum.jl#27]
When thinking about how to document `@einsimd`, I noticed that `@simd` only gets added to inner loops of contractions, but not to "straight" loops, e.g.

```julia
julia> @macroexpand Einsum.@einsimd a[i] = b[i]
quote  
    let
        begin 
            $(Expr(:inbounds, true))
            begin  
                local i 
                for i = 1:min(size(a, 1), size(b, 1)) 
                    a[i] = b[i]
                end
            end
            $(Expr(:inbounds, :pop))
        end
    end
    a
end
```

Shouldn't this be vectorized, too? 

More general: would the right behaviour for `@einsimd` be to always add `@simd` to the innermost loop? 

And for documentation (since I don't know much about SIMD): for which loops or kinds of operations does this actually make sense? Any good ressources I can link to?

**Comment by ahwillia** [comment]
This was an experimental feature. I don't know too much about SIMD either, but you could try looking here: https://github.com/eschnett/SIMD.jl

**Comment by phipsgabler** [comment]
Ok, doing my homework now... [This article](https://software.intel.com/en-us/articles/vectorization-in-julia) is rather old, but seems to be quite in-depth. Other than that, there's also quite a bit in the [docs](https://docs.julialang.org/en/stable/manual/performance-tips/#Performance-Annotations-1).

Concluding, I'd say that `@einsimd` should always add `@simd` to the innermost loop, since both "vector-loops" and "reduction loops" are in general in scope for it. Other than that, it's a choice for the user. We are already using `@inbounds` everywhere, so the only thing they have to make sure is for the operation actually to make sense in terms of the operations and  stride accesses.

Another thing which we should maybe support, then, is something like `@ein(simd|sum) @fastmath <expr>`.

**Comment by phipsgabler** [comment]
I think adding it to all loops is as simple as in the `simd` branch I created. Seems to work.

**Comment by phipsgabler** [comment]
I think adding it to all loops is as simple as in the `simd` branch I created. Seems to work.
