### ISSUE TITLE
Tag for 1.0

### ISSUE THREAD

**Issue by mcabbott** [ahwillia/Einsum.jl#33]
I just saw that the v0.3.0 tag here never made it into the registry:  https://github.com/JuliaLang/METADATA.jl/pull/16732 . Thus pkg on 1.0 downloads a version which doesn't work. Do you think you could tag a new version, @phipsgabler ?

**Comment by phipsgabler** [comment]
Done.  But I must admit that I'm new to the whole publishing business, so unsure if that's all there's to do...

**Comment by mcabbott** [comment]
I don't understand `project.toml` well but CI had a complaint about the UUID it provides. Maybe v0.4.1 will pass?

**Comment by phipsgabler** [comment]
Seems to work, thanks. 

I do prefer the Pkg3 interface, hence the Project.toml, but yeah, there's a lot of redundancy one always forgets (specifyfying the version manually, keeping dependencies in REQUIRE as well)... I hope that will be fixed soon, once they move forward in how the registration process works.

**Comment by mcabbott** [comment]
Seems to all be working now. Yes it sounds like the future will be great, but the present is pretty confusing... Anyway, many thanks!
