### ISSUE TITLE
Einsum over variable indices

### ISSUE THREAD

**Issue by GiggleLiu** [ahwillia/Einsum.jl#36]
Since `@einsum` interface is a macro, I wonder if it is possible to take variable as input indices? like
```julia console
julia> Is = (1,2,3)
(1, 2, 3)

julia> Js = (2,3,4)
(2, 3, 4)

julia> Ks = (1,4)
(1, 4)

julia> einsum(((Is, Js), Ks), A, B, C)
```

**Comment by phipsgabler** [comment]
Unfortunately, we are not using some smart intermediate representation -- just direct code generation of nested loops.  So this is not easily possible with Einsum, I guess.

But [TensorOperations](https://github.com/Jutho/TensorOperations.jl) exposes its [internal functions](https://jutho.github.io/TensorOperations.jl/stable/implementation/#Building-blocks-1) -- if your use case consists only of "proper" contractions, you could have a look at the `contract!` function there, I guess.

**Comment by GiggleLiu** [comment]
Thanks for your suggestions. 👍
